### ISSUE TITLE
Fork the original scratch3-bridge repo paulolc/scratch3-bridge to allow the community to collaborate

### ISSUE THREAD

**Issue by paulolc** [Project-Arachne/scratch3-bridge#4]
This repo is missing the connection to the original repo at https://github.com/paulolc/scratch3-bridge. 

This can bring confusion the community and tamper any collaboration efforts.

Fork the original scratch3-bridge repo paulolc/scratch3-bridge and do pull-requests if you want

This way the community will also be aware of this fork and contribute to it if it sees fit.

**Comment by J0hnL0cke** [comment]
Done, deleting this repo
